In [ ]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 8.9 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.8.0

In [ ]:
import pandas as pd
import numpy as np
import optuna
import tensorflow as tf

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import Dense


from tensorflow.keras.optimizers import SGD, Adam, RMSprop, Adagrad, Adadelta, Nadam


from sklearn.metrics import roc_auc_score

In [ ]:
data = pd.read_csv('Employee.csv')

data

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [ ]:
data.describe(include='all')

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
count,4653,4653.000000,4653,4653.000000,4653.000000,4653,4653,4653.000000,4653.000000
unique,3,NaN,3,NaN,NaN,2,2,NaN,NaN
top,Bachelors,NaN,Bangalore,NaN,NaN,Male,No,NaN,NaN
freq,3601,NaN,2228,NaN,NaN,2778,4175,NaN,NaN
mean,NaN,2015.062970,NaN,2.698259,29.393295,NaN,NaN,2.905652,0.343864
std,NaN,1.863377,NaN,0.561435,4.826087,NaN,NaN,1.558240,0.475047
min,NaN,2012.000000,NaN,1.000000,22.000000,NaN,NaN,0.000000,0.000000
25%,NaN,2013.000000,NaN,3.000000,26.000000,NaN,NaN,2.000000,0.000000
50%,NaN,2015.000000,NaN,3.000000,28.000000,NaN,NaN,3.000000,0.000000
75%,NaN,2017.000000,NaN,3.000000,32.000000,NaN,NaN,4.000000,1.000000
max,NaN,2018.000000,NaN,3.000000,41.000000,NaN,NaN,7.000000,1.000000

In [ ]:
data.isnull().sum()

Education                    0
JoiningYear                  0
City                         0
PaymentTier                  0
Age                          0
Gender                       0
EverBenched                  0
ExperienceInCurrentDomain    0
LeaveOrNot                   0
dtype: int64

In [ ]:
data = pd.get_dummies(data, drop_first=True)

data

,JoiningYear,PaymentTier,Age,ExperienceInCurrentDomain,LeaveOrNot,Education_Masters,Education_PHD,City_New Delhi,City_Pune,Gender_Male,EverBenched_Yes
0,2017,3,34,0,0,False,False,False,False,True,False
1,2013,1,28,3,1,False,False,False,True,False,False
2,2014,3,38,2,0,False,False,True,False,False,False
3,2016,3,27,5,1,True,False,False,False,True,False
4,2017,3,24,2,1,True,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...
4648,2013,3,26,4,0,False,False,False,False,False,False
4649,2013,2,37,2,1,True,False,False,True,True,False
4650,2018,3,27,5,1,True,False,True,False,True,False
4651,2012,3,30,2,0,False,False,False,False,True,True
4652,2015,3,33,4,0,False,False,False,False,True,True

In [ ]:
targets = data['LeaveOrNot']

inputs = data.drop(['LeaveOrNot'],axis=1)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(inputs)

scaled = scaler.transform(inputs)

inputs_scaled = pd.DataFrame(scaled, columns=inputs.columns)

inputs_scaled

,JoiningYear,PaymentTier,Age,ExperienceInCurrentDomain,Education_Masters,Education_PHD,City_New Delhi,City_Pune,Gender_Male,EverBenched_Yes
0,1.039638,0.537503,0.954645,-1.864901,-0.480575,-0.200022,-0.575282,-0.612041,0.821551,-0.338365
1,-1.107233,-3.025177,-0.288732,0.060554,-0.480575,-0.200022,-0.575282,1.633878,-1.217210,-0.338365
2,-0.570515,0.537503,1.783563,-0.581264,-0.480575,-0.200022,1.738277,-0.612041,-1.217210,-0.338365
3,0.502921,0.537503,-0.495961,1.344191,2.080840,-0.200022,-0.575282,-0.612041,0.821551,-0.338365
4,1.039638,0.537503,-1.117650,-0.581264,2.080840,-0.200022,-0.575282,1.633878,0.821551,2.955387
...,...,...,...,...,...,...,...,...,...,...
4648,-1.107233,0.537503,-0.703191,0.702373,-0.480575,-0.200022,-0.575282,-0.612041,-1.217210,-0.338365
4649,-1.107233,-1.243837,1.576334,-0.581264,2.080840,-0.200022,-0.575282,1.633878,0.821551,-0.338365
4650,1.576356,0.537503,-0.495961,1.344191,2.080840,-0.200022,1.738277,-0.612041,0.821551,-0.338365
4651,-1.643951,0.537503,0.125727,-0.581264,-0.480575,-0.200022,-0.575282,-0.612041,0.821551,2.955387
4652,-0.033797,0.537503,0.747416,0.702373,-0.480575,-0.200022,-0.575282,-0.612041,0.821551,2.955387

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(inputs_scaled, targets, test_size=0.2, random_state=42)

In [ ]:
def create_model(trial):
    model = Sequential()

    model.add(Dense(units=trial.suggest_int('units_layer1', 6, 32), activation='relu'))
    model.add(Dense(units=trial.suggest_int('units_layer2', 6, 32), activation='relu'))
    model.add(Dense(units=1, activation='sigmoid'))


    optimizer_name = trial.suggest_categorical('optimizer', ['adam', 'sgd', 'rmsprop', 'adagrad'])
    learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

    if optimizer_name == 'adam':
        optimizer = Adam(learning_rate=learning_rate)
    elif optimizer_name == 'sgd':
        optimizer = SGD(learning_rate=learning_rate)
    elif optimizer_name == 'rmsprop':
        optimizer = RMSprop(learning_rate=learning_rate)
    elif optimizer_name == 'adagrad':
        optimizer = Adagrad(learning_rate=learning_rate)

    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['AUC'])

    return model

In [ ]:
def optimal(trial):


    epochs = trial.suggest_int('epochs', 10, 50)
    batch_size = trial.suggest_int('batch_size', 16, 64)

    model = create_model(trial)

    history = model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size)

    y_pred = model.predict(X_test)
    auc = roc_auc_score(y_test, y_pred)

    return auc

study = optuna.create_study(direction='maximize')
study.optimize(optimal, n_trials=10)

print(f"Best trial: {study.best_trial.value}")
print(f"Best hyperparameters: {study.best_trial.params}")

[I 2026-04-18 10:05:51,684] A new study created in memory with name: no-name-49222b9b-7118-4e37-a7e7-981f48b8b739

Epoch 1/19

/tmp/ipykernel_1867/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

71/71 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - AUC: 0.5354 - loss: 0.6741
Epoch 2/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - AUC: 0.5353 - loss: 0.6740
Epoch 3/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - AUC: 0.5352 - loss: 0.6740
Epoch 4/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - AUC: 0.5353 - loss: 0.6739
Epoch 5/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - AUC: 0.5354 - loss: 0.6739
Epoch 6/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - AUC: 0.5353 - loss: 0.6739
Epoch 7/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - AUC: 0.5356 - loss: 0.6738
Epoch 8/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - AUC: 0.5358 - loss: 0.6738
Epoch 9/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - AUC: 0.5360 - loss: 0.6737
Epoch 10/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - AUC: 0.5360 - loss: 0.6737
Epoch 11/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - AUC: 0.5361 - loss: 0.6736
Epoch 12/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - AUC: 0.5361 - loss: 0.6736
Epoch 13/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - AUC: 0.5362 - loss: 0.6735
Epoch 14/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - AUC: 0.5363 - loss: 0.6735
Epoch 15/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - AUC: 0.5366 - loss: 0.6734
Epoch 16/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - AUC: 0.5366 - loss: 0.6734
Epoch 17/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - AUC: 0.5366 - loss: 0.6734
Epoch 18/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - AUC: 0.5366 - loss: 0.6733
Epoch 19/19
71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - AUC: 0.5366 - loss: 0.6733
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

[I 2026-04-18 10:06:08,429] Trial 0 finished with value: 0.512568306010929 and parameters: {'epochs': 19, 'batch_size': 53, 'units_layer1': 22, 'units_layer2': 6, 'optimizer': 'sgd', 'learning_rate': 1.7995890543118157e-05}. Best is trial 0 with value: 0.512568306010929.

Epoch 1/31

/tmp/ipykernel_1867/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

110/110 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - AUC: 0.4733 - loss: 0.6829
Epoch 2/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.6605 - loss: 0.6174
Epoch 3/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7120 - loss: 0.5867
Epoch 4/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7347 - loss: 0.5668
Epoch 5/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7507 - loss: 0.5527
Epoch 6/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7623 - loss: 0.5416
Epoch 7/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7715 - loss: 0.5328
Epoch 8/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7792 - loss: 0.5251
Epoch 9/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7847 - loss: 0.5183
Epoch 10/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7891 - loss: 0.5126
Epoch 11/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7931 - loss: 0.5074
Epoch 12/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7970 - loss: 0.5028
Epoch 13/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8007 - loss: 0.4986
Epoch 14/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8028 - loss: 0.4946
Epoch 15/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8052 - loss: 0.4908
Epoch 16/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8075 - loss: 0.4874
Epoch 17/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8100 - loss: 0.4840
Epoch 18/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8119 - loss: 0.4810
Epoch 19/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8144 - loss: 0.4781
Epoch 20/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8159 - loss: 0.4754
Epoch 21/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8178 - loss: 0.4729
Epoch 22/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8190 - loss: 0.4706
Epoch 23/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8206 - loss: 0.4685
Epoch 24/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8218 - loss: 0.4664
Epoch 25/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8235 - loss: 0.4644
Epoch 26/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8246 - loss: 0.4625
Epoch 27/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8258 - loss: 0.4607
Epoch 28/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8270 - loss: 0.4589
Epoch 29/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8284 - loss: 0.4574
Epoch 30/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8297 - loss: 0.4557
Epoch 31/31
110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8308 - loss: 0.4542
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

[I 2026-04-18 10:06:20,398] Trial 1 finished with value: 0.864161687349982 and parameters: {'epochs': 31, 'batch_size': 34, 'units_layer1': 27, 'units_layer2': 24, 'optimizer': 'adagrad', 'learning_rate': 0.007538224086412058}. Best is trial 1 with value: 0.864161687349982.

Epoch 1/40

/tmp/ipykernel_1867/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

129/129 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.5446 - loss: 0.6685
Epoch 2/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.5619 - loss: 0.6497
Epoch 3/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - AUC: 0.5822 - loss: 0.6355
Epoch 4/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - AUC: 0.6134 - loss: 0.6227
Epoch 5/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.6402 - loss: 0.6106
Epoch 6/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.6676 - loss: 0.5989
Epoch 7/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.6915 - loss: 0.5878
Epoch 8/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.7091 - loss: 0.5775
Epoch 9/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7217 - loss: 0.5683
Epoch 10/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7319 - loss: 0.5602
Epoch 11/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7401 - loss: 0.5530
Epoch 12/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7465 - loss: 0.5467
Epoch 13/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7524 - loss: 0.5410
Epoch 14/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7582 - loss: 0.5359
Epoch 15/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7627 - loss: 0.5311
Epoch 16/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7670 - loss: 0.5268
Epoch 17/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7706 - loss: 0.5228
Epoch 18/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7737 - loss: 0.5190
Epoch 19/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7769 - loss: 0.5156
Epoch 20/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7795 - loss: 0.5122
Epoch 21/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7823 - loss: 0.5093
Epoch 22/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7842 - loss: 0.5065
Epoch 23/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7865 - loss: 0.5039
Epoch 24/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7884 - loss: 0.5013
Epoch 25/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7899 - loss: 0.4989
Epoch 26/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7921 - loss: 0.4966
Epoch 27/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7939 - loss: 0.4944
Epoch 28/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7954 - loss: 0.4924
Epoch 29/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7971 - loss: 0.4905
Epoch 30/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7984 - loss: 0.4886
Epoch 31/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8000 - loss: 0.4866
Epoch 32/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8016 - loss: 0.4847
Epoch 33/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8033 - loss: 0.4832
Epoch 34/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8040 - loss: 0.4815
Epoch 35/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8053 - loss: 0.4799
Epoch 36/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8065 - loss: 0.4783
Epoch 37/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8077 - loss: 0.4771
Epoch 38/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8091 - loss: 0.4756
Epoch 39/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8103 - loss: 0.4741
Epoch 40/40
129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8118 - loss: 0.4727
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

[I 2026-04-18 10:06:35,003] Trial 2 finished with value: 0.8479725243858842 and parameters: {'epochs': 40, 'batch_size': 29, 'units_layer1': 13, 'units_layer2': 20, 'optimizer': 'adam', 'learning_rate': 0.00020721962231358353}. Best is trial 1 with value: 0.864161687349982.

Epoch 1/34

/tmp/ipykernel_1867/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

85/85 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - AUC: 0.4242 - loss: 0.8143
Epoch 2/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.5256 - loss: 0.6841
Epoch 3/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.6445 - loss: 0.6214
Epoch 4/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.6945 - loss: 0.5907
Epoch 5/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.7197 - loss: 0.5712
Epoch 6/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - AUC: 0.7357 - loss: 0.5577
Epoch 7/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7461 - loss: 0.5479
Epoch 8/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7543 - loss: 0.5401
Epoch 9/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7605 - loss: 0.5336
Epoch 10/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7667 - loss: 0.5279
Epoch 11/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7726 - loss: 0.5225
Epoch 12/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7772 - loss: 0.5178
Epoch 13/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7816 - loss: 0.5133
Epoch 14/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7856 - loss: 0.5092
Epoch 15/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7894 - loss: 0.5054
Epoch 16/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7929 - loss: 0.5015
Epoch 17/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7960 - loss: 0.4980
Epoch 18/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7987 - loss: 0.4948
Epoch 19/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8015 - loss: 0.4916
Epoch 20/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8040 - loss: 0.4886
Epoch 21/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8063 - loss: 0.4857
Epoch 22/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8088 - loss: 0.4830
Epoch 23/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8109 - loss: 0.4804
Epoch 24/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8130 - loss: 0.4780
Epoch 25/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8152 - loss: 0.4756
Epoch 26/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8168 - loss: 0.4735
Epoch 27/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8189 - loss: 0.4712
Epoch 28/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8200 - loss: 0.4697
Epoch 29/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8215 - loss: 0.4679
Epoch 30/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8229 - loss: 0.4662
Epoch 31/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8244 - loss: 0.4646
Epoch 32/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8256 - loss: 0.4628
Epoch 33/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8262 - loss: 0.4612
Epoch 34/34
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8282 - loss: 0.4596
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

[I 2026-04-18 10:06:44,342] Trial 3 finished with value: 0.8593585618712016 and parameters: {'epochs': 34, 'batch_size': 44, 'units_layer1': 14, 'units_layer2': 11, 'optimizer': 'rmsprop', 'learning_rate': 0.00036111135682984725}. Best is trial 1 with value: 0.864161687349982.

Epoch 1/19

/tmp/ipykernel_1867/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

69/69 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - AUC: 0.4083 - loss: 0.7022
Epoch 2/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4904 - loss: 0.6687
Epoch 3/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.6161 - loss: 0.6422
Epoch 4/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.6768 - loss: 0.6182
Epoch 5/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7016 - loss: 0.5976
Epoch 6/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7183 - loss: 0.5801
Epoch 7/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7271 - loss: 0.5662
Epoch 8/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7374 - loss: 0.5548
Epoch 9/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7455 - loss: 0.5458
Epoch 10/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7513 - loss: 0.5384
Epoch 11/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7582 - loss: 0.5321
Epoch 12/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7638 - loss: 0.5264
Epoch 13/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7693 - loss: 0.5214
Epoch 14/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7730 - loss: 0.5172
Epoch 15/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7769 - loss: 0.5131
Epoch 16/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.7804 - loss: 0.5092
Epoch 17/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.7836 - loss: 0.5056
Epoch 18/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.7871 - loss: 0.5022
Epoch 19/19
69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.7896 - loss: 0.4991
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

[I 2026-04-18 10:06:49,519] Trial 4 finished with value: 0.830200194065676 and parameters: {'epochs': 19, 'batch_size': 54, 'units_layer1': 24, 'units_layer2': 32, 'optimizer': 'rmsprop', 'learning_rate': 0.00022792629536359636}. Best is trial 1 with value: 0.864161687349982.

Epoch 1/46

/tmp/ipykernel_1867/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

117/117 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.6108 - loss: 0.6448
Epoch 2/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7115 - loss: 0.5934
Epoch 3/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7366 - loss: 0.5688
Epoch 4/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7535 - loss: 0.5526
Epoch 5/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7651 - loss: 0.5408
Epoch 6/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7733 - loss: 0.5316
Epoch 7/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7802 - loss: 0.5236
Epoch 8/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7858 - loss: 0.5169
Epoch 9/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7904 - loss: 0.5112
Epoch 10/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7947 - loss: 0.5056
Epoch 11/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7992 - loss: 0.5004
Epoch 12/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8028 - loss: 0.4956
Epoch 13/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8061 - loss: 0.4908
Epoch 14/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8095 - loss: 0.4866
Epoch 15/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8126 - loss: 0.4823
Epoch 16/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8151 - loss: 0.4782
Epoch 17/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8174 - loss: 0.4745
Epoch 18/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8202 - loss: 0.4710
Epoch 19/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8227 - loss: 0.4673
Epoch 20/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8253 - loss: 0.4641
Epoch 21/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8270 - loss: 0.4611
Epoch 22/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8299 - loss: 0.4580
Epoch 23/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8317 - loss: 0.4551
Epoch 24/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8335 - loss: 0.4525
Epoch 25/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8356 - loss: 0.4499
Epoch 26/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8376 - loss: 0.4471
Epoch 27/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8397 - loss: 0.4446
Epoch 28/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8401 - loss: 0.4427
Epoch 29/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8430 - loss: 0.4400
Epoch 30/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8438 - loss: 0.4378
Epoch 31/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8452 - loss: 0.4357
Epoch 32/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8471 - loss: 0.4335
Epoch 33/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8477 - loss: 0.4315
Epoch 34/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8485 - loss: 0.4298
Epoch 35/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8492 - loss: 0.4280
Epoch 36/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8500 - loss: 0.4265
Epoch 37/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8519 - loss: 0.4247
Epoch 38/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8522 - loss: 0.4232
Epoch 39/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.8529 - loss: 0.4215
Epoch 40/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.8536 - loss: 0.4200
Epoch 41/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - AUC: 0.8547 - loss: 0.4187
Epoch 42/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.8551 - loss: 0.4171
Epoch 43/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.8560 - loss: 0.4158
Epoch 44/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.8568 - loss: 0.4146
Epoch 45/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - AUC: 0.8570 - loss: 0.4133
Epoch 46/46
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8574 - loss: 0.4124
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

[I 2026-04-18 10:07:04,872] Trial 5 finished with value: 0.877358153311884 and parameters: {'epochs': 46, 'batch_size': 32, 'units_layer1': 25, 'units_layer2': 16, 'optimizer': 'adam', 'learning_rate': 0.0002846654823913909}. Best is trial 5 with value: 0.877358153311884.

Epoch 1/47

/tmp/ipykernel_1867/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

85/85 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - AUC: 0.5575 - loss: 0.6471
Epoch 2/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7289 - loss: 0.5631
Epoch 3/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7627 - loss: 0.5333
Epoch 4/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7845 - loss: 0.5124
Epoch 5/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7937 - loss: 0.4996
Epoch 6/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8013 - loss: 0.4895
Epoch 7/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8036 - loss: 0.4836
Epoch 8/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8082 - loss: 0.4780
Epoch 9/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8112 - loss: 0.4735
Epoch 10/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8168 - loss: 0.4688
Epoch 11/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8193 - loss: 0.4642
Epoch 12/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8222 - loss: 0.4603
Epoch 13/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8257 - loss: 0.4560
Epoch 14/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8289 - loss: 0.4526
Epoch 15/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8315 - loss: 0.4483
Epoch 16/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8340 - loss: 0.4449
Epoch 17/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8367 - loss: 0.4406
Epoch 18/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8402 - loss: 0.4360
Epoch 19/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8421 - loss: 0.4322
Epoch 20/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8442 - loss: 0.4282
Epoch 21/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8453 - loss: 0.4253
Epoch 22/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8468 - loss: 0.4219
Epoch 23/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8483 - loss: 0.4196
Epoch 24/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8507 - loss: 0.4162
Epoch 25/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8512 - loss: 0.4143
Epoch 26/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8535 - loss: 0.4117
Epoch 27/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8528 - loss: 0.4095
Epoch 28/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8552 - loss: 0.4074
Epoch 29/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8559 - loss: 0.4051
Epoch 30/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8590 - loss: 0.4021
Epoch 31/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8582 - loss: 0.4016
Epoch 32/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8605 - loss: 0.3993
Epoch 33/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8601 - loss: 0.3982
Epoch 34/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8607 - loss: 0.3969
Epoch 35/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8623 - loss: 0.3948
Epoch 36/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8627 - loss: 0.3940
Epoch 37/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8625 - loss: 0.3934
Epoch 38/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8637 - loss: 0.3917
Epoch 39/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8638 - loss: 0.3902
Epoch 40/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.8648 - loss: 0.3893
Epoch 41/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.8655 - loss: 0.3886
Epoch 42/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - AUC: 0.8657 - loss: 0.3876
Epoch 43/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.8664 - loss: 0.3862
Epoch 44/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.8671 - loss: 0.3855
Epoch 45/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.8677 - loss: 0.3843
Epoch 46/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - AUC: 0.8679 - loss: 0.3842
Epoch 47/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8691 - loss: 0.3830
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

[I 2026-04-18 10:07:16,902] Trial 6 finished with value: 0.8857106378632348 and parameters: {'epochs': 47, 'batch_size': 44, 'units_layer1': 10, 'units_layer2': 24, 'optimizer': 'rmsprop', 'learning_rate': 0.0013227354567160255}. Best is trial 6 with value: 0.8857106378632348.

Epoch 1/20

/tmp/ipykernel_1867/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

144/144 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - AUC: 0.4650 - loss: 0.7451
Epoch 2/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4654 - loss: 0.7442
Epoch 3/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4660 - loss: 0.7435
Epoch 4/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4661 - loss: 0.7429
Epoch 5/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - AUC: 0.4663 - loss: 0.7423
Epoch 6/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4665 - loss: 0.7418
Epoch 7/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4666 - loss: 0.7414
Epoch 8/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4668 - loss: 0.7410
Epoch 9/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4670 - loss: 0.7406
Epoch 10/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4671 - loss: 0.7402
Epoch 11/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4672 - loss: 0.7399
Epoch 12/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4675 - loss: 0.7395
Epoch 13/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4676 - loss: 0.7392
Epoch 14/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4677 - loss: 0.7389
Epoch 15/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4679 - loss: 0.7386
Epoch 16/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4681 - loss: 0.7383
Epoch 17/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4684 - loss: 0.7380
Epoch 18/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - AUC: 0.4685 - loss: 0.7378
Epoch 19/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4687 - loss: 0.7375
Epoch 20/20
144/144 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.4688 - loss: 0.7373
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

[I 2026-04-18 10:07:24,584] Trial 7 finished with value: 0.49369031203717884 and parameters: {'epochs': 20, 'batch_size': 26, 'units_layer1': 21, 'units_layer2': 25, 'optimizer': 'adagrad', 'learning_rate': 1.748412220017089e-05}. Best is trial 6 with value: 0.8857106378632348.

Epoch 1/22

/tmp/ipykernel_1867/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

96/96 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - AUC: 0.3403 - loss: 0.7925
Epoch 2/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.3437 - loss: 0.7816
Epoch 3/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.3473 - loss: 0.7740
Epoch 4/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.3501 - loss: 0.7679
Epoch 5/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - AUC: 0.3529 - loss: 0.7628
Epoch 6/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - AUC: 0.3558 - loss: 0.7582
Epoch 7/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - AUC: 0.3583 - loss: 0.7542
Epoch 8/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.3611 - loss: 0.7505
Epoch 9/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.3633 - loss: 0.7472
Epoch 10/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.3659 - loss: 0.7441
Epoch 11/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.3675 - loss: 0.7412
Epoch 12/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.3700 - loss: 0.7386
Epoch 13/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.3716 - loss: 0.7361
Epoch 14/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.3737 - loss: 0.7337
Epoch 15/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.3752 - loss: 0.7315
Epoch 16/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.3770 - loss: 0.7294
Epoch 17/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.3786 - loss: 0.7275
Epoch 18/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.3806 - loss: 0.7256
Epoch 19/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.3823 - loss: 0.7238
Epoch 20/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.3842 - loss: 0.7220
Epoch 21/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.3860 - loss: 0.7204
Epoch 22/22
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.3875 - loss: 0.7188
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

[I 2026-04-18 10:07:31,950] Trial 8 finished with value: 0.3708850416219805 and parameters: {'epochs': 22, 'batch_size': 39, 'units_layer1': 13, 'units_layer2': 11, 'optimizer': 'adagrad', 'learning_rate': 0.00036489741804043136}. Best is trial 6 with value: 0.8857106378632348.

Epoch 1/48

/tmp/ipykernel_1867/3644950783.py:12: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 1e-2)

101/101 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - AUC: 0.6096 - loss: 0.6938
Epoch 2/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.6548 - loss: 0.6269
Epoch 3/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.6847 - loss: 0.6044
Epoch 4/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7064 - loss: 0.5899
Epoch 5/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7219 - loss: 0.5783
Epoch 6/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7310 - loss: 0.5686
Epoch 7/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7392 - loss: 0.5608
Epoch 8/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7453 - loss: 0.5543
Epoch 9/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7505 - loss: 0.5488
Epoch 10/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7547 - loss: 0.5443
Epoch 11/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7590 - loss: 0.5401
Epoch 12/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7629 - loss: 0.5364
Epoch 13/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7667 - loss: 0.5328
Epoch 14/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7697 - loss: 0.5296
Epoch 15/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7725 - loss: 0.5266
Epoch 16/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7753 - loss: 0.5237
Epoch 17/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7779 - loss: 0.5208
Epoch 18/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7807 - loss: 0.5182
Epoch 19/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7835 - loss: 0.5155
Epoch 20/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7855 - loss: 0.5129
Epoch 21/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7872 - loss: 0.5106
Epoch 22/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7893 - loss: 0.5082
Epoch 23/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7916 - loss: 0.5060
Epoch 24/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7935 - loss: 0.5038
Epoch 25/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7953 - loss: 0.5015
Epoch 26/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.7969 - loss: 0.4995
Epoch 27/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.7984 - loss: 0.4975
Epoch 28/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.8000 - loss: 0.4956
Epoch 29/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8016 - loss: 0.4937
Epoch 30/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.8031 - loss: 0.4918
Epoch 31/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - AUC: 0.8045 - loss: 0.4901
Epoch 32/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.8062 - loss: 0.4883
Epoch 33/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.8074 - loss: 0.4865
Epoch 34/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8086 - loss: 0.4849
Epoch 35/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - AUC: 0.8099 - loss: 0.4832
Epoch 36/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.8112 - loss: 0.4816
Epoch 37/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8127 - loss: 0.4801
Epoch 38/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8136 - loss: 0.4786
Epoch 39/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8147 - loss: 0.4772
Epoch 40/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8158 - loss: 0.4758
Epoch 41/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8168 - loss: 0.4742
Epoch 42/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8176 - loss: 0.4730
Epoch 43/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8186 - loss: 0.4719
Epoch 44/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8194 - loss: 0.4705
Epoch 45/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8204 - loss: 0.4693
Epoch 46/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8211 - loss: 0.4681
Epoch 47/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8222 - loss: 0.4668
Epoch 48/48
101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8228 - loss: 0.4657
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

[I 2026-04-18 10:07:45,141] Trial 9 finished with value: 0.8567897451611255 and parameters: {'epochs': 48, 'batch_size': 37, 'units_layer1': 23, 'units_layer2': 30, 'optimizer': 'sgd', 'learning_rate': 0.008164707239111526}. Best is trial 6 with value: 0.8857106378632348.

Best trial: 0.8857106378632348
Best hyperparameters: {'epochs': 47, 'batch_size': 44, 'units_layer1': 10, 'units_layer2': 24, 'optimizer': 'rmsprop', 'learning_rate': 0.0013227354567160255}

In [ ]:
best_params = study.best_trial.params

best_params

{'epochs': 47,
 'batch_size': 44,
 'units_layer1': 10,
 'units_layer2': 24,
 'optimizer': 'rmsprop',
 'learning_rate': 0.0013227354567160255}

In [ ]:

best_model = Sequential()
best_model.add(Dense(units=best_params['units_layer1'], activation='relu'))
best_model.add(Dense(units=best_params['units_layer2'], activation='relu'))
best_model.add(Dense(1, activation='sigmoid'))

In [ ]:
if best_params['optimizer'] == 'adam':
    best_optimizer = Adam(learning_rate=best_params['learning_rate'])
elif best_params['optimizer'] == 'sgd':
    best_optimizer = SGD(learning_rate=best_params['learning_rate'])
elif best_params['optimizer'] == 'rmsprop':
    best_optimizer = RMSprop(learning_rate=best_params['learning_rate'])
elif best_params['optimizer'] == 'adagrad':
    best_optimizer = Adagrad(learning_rate=best_params['learning_rate'])

In [ ]:
best_model.compile(optimizer=best_optimizer, loss='binary_crossentropy', metrics=['AUC'])

In [ ]:
def evaluate(model, X_train, y_train, X_test, y_test):

    model.fit(X_train, y_train, epochs=47, batch_size=best_params['batch_size'])


    y_train_prob = model.predict(X_train)



    y_test_prob = model.predict(X_test)



    roc_train_prob = roc_auc_score(y_train, y_train_prob)
    gini_train_prob = roc_train_prob * 2 - 1



    roc_test_prob = roc_auc_score(y_test, y_test_prob)
    gini_test_prob = roc_test_prob * 2 - 1


    results = pd.DataFrame({
        'Dataset': ['Train', 'Test'],
        'Gini': [gini_train_prob * 100, gini_test_prob * 100],

    })

    return results

In [ ]:
evaluate(best_model, X_train, y_train, X_test, y_test)

Epoch 1/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - AUC: 0.7037 - loss: 0.5931
Epoch 2/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.7395 - loss: 0.5709
Epoch 3/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - AUC: 0.7593 - loss: 0.5519
Epoch 4/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - AUC: 0.7733 - loss: 0.5345
Epoch 5/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - AUC: 0.7844 - loss: 0.5191
Epoch 6/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - AUC: 0.7923 - loss: 0.5076
Epoch 7/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - AUC: 0.7986 - loss: 0.4973
Epoch 8/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - AUC: 0.8047 - loss: 0.4894
Epoch 9/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - AUC: 0.8113 - loss: 0.4816
Epoch 10/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - AUC: 0.8149 - loss: 0.4756
Epoch 11/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8199 - loss: 0.4696
Epoch 12/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8258 - loss: 0.4628
Epoch 13/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8289 - loss: 0.4575
Epoch 14/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8317 - loss: 0.4533
Epoch 15/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8354 - loss: 0.4477
Epoch 16/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8367 - loss: 0.4436
Epoch 17/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8389 - loss: 0.4393
Epoch 18/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8419 - loss: 0.4346
Epoch 19/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8440 - loss: 0.4303
Epoch 20/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8458 - loss: 0.4267
Epoch 21/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8480 - loss: 0.4227
Epoch 22/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8491 - loss: 0.4198
Epoch 23/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8516 - loss: 0.4160
Epoch 24/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8537 - loss: 0.4128
Epoch 25/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8531 - loss: 0.4107
Epoch 26/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8552 - loss: 0.4074
Epoch 27/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8562 - loss: 0.4054
Epoch 28/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8601 - loss: 0.4017
Epoch 29/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8604 - loss: 0.3995
Epoch 30/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8619 - loss: 0.3977
Epoch 31/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8620 - loss: 0.3960
Epoch 32/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8639 - loss: 0.3934
Epoch 33/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8648 - loss: 0.3910
Epoch 34/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8670 - loss: 0.3878
Epoch 35/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8677 - loss: 0.3872
Epoch 36/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8682 - loss: 0.3852
Epoch 37/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8693 - loss: 0.3834
Epoch 38/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8701 - loss: 0.3821
Epoch 39/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8709 - loss: 0.3809
Epoch 40/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8722 - loss: 0.3798
Epoch 41/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8724 - loss: 0.3792
Epoch 42/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8720 - loss: 0.3784
Epoch 43/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8727 - loss: 0.3779
Epoch 44/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8722 - loss: 0.3776
Epoch 45/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8743 - loss: 0.3761
Epoch 46/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8732 - loss: 0.3758
Epoch 47/47
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - AUC: 0.8738 - loss: 0.3753
117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

  Dataset       Gini
0   Train  75.684992
1    Test  77.952607